name: json_data_explorer
description: A highly customizable widget to render and interact with JSON objects.
version: 0.2.0
repository: https://github.com/rows/json_data_explorer
homepage: https://github.com/rows/json_data_explorer
issue_tracker: https://github.com/rows/json_data_explorer/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.2
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  rows_lint: ^0.1.1
  mocktail: ^0.3.0
  golden_toolkit: ^0.13.0

flutter:
  uses-material-design: true