name: json_data_explorer
description: A Flutter package to display json objects.
version: 0.0.1
repository: https://github.com/rows/json-data-explorer
homepage: https://github.com/rows/json-data-explorer

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.2.3
  provider: ^6.0.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  rows_lint: 0.1.0
  mocktail: ^0.3.0
